"""The bill of quantities for the synthetic project: eleven trade groups, ~180 priced items.

Authored rather than generated at random, for two reasons. A quantity surveyor reading it should
recognise the trade breakdown of a G+4 residential tower, because the bundle's second job is to be
shown to one; and the item numbers the defect specification names have to exist, which a random
catalogue cannot guarantee.

Rates are representative of Indian building work and are **not** taken from any published schedule.
Copying CPWD DSR figures would make the file a derivative of a specific edition and would invite the
exact confusion Tier 5 exists to prevent — a synthetic document that looks sourced. They are round,
plausible, and fictional.

Quantities follow a real building's proportions: concrete and steel dominate the structure, finishes
dominate the item *count*, and the finishing trades carry the small repetitive lines where
measurement errors actually live.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal
from typing import Final

__all__ = ["CATALOGUE", "BoqItem", "TradeGroup", "contract_value", "item_by_number", "items"]


@dataclass(frozen=True, slots=True)
class BoqItem:
    """One priced line of the contract bill."""

    number: str
    description: str
    unit: str
    quantity: Decimal
    rate: Decimal
    first_period: int
    """The RA bill in which this trade first appears. Structure early, finishes late."""

    last_period: int
    """The RA bill by which it is complete, absent a planted defect."""

    @property
    def amount(self) -> Decimal:
        return (self.quantity * self.rate).quantize(Decimal("0.01"))


@dataclass(frozen=True, slots=True)
class TradeGroup:
    number: str
    title: str
    items: tuple[BoqItem, ...]


def _q(value: str) -> Decimal:
    return Decimal(value)


def _group(
    number: str,
    title: str,
    rows: tuple[tuple[str, str, str, str, str, int, int], ...],
) -> TradeGroup:
    """Build a group from compact tuples: (item, description, unit, qty, rate, first, last)."""
    return TradeGroup(
        number=number,
        title=title,
        items=tuple(
            BoqItem(
                number=item,
                description=description,
                unit=unit,
                quantity=_q(quantity),
                rate=_q(rate),
                first_period=first,
                last_period=last,
            )
            for item, description, unit, quantity, rate, first, last in rows
        ),
    )


CATALOGUE: Final[tuple[TradeGroup, ...]] = (
    _group(
        "1",
        "Earthwork and Site Preparation",
        (
            (
                "1.1.1",
                "Clearing site of shrubs, vegetation and rubbish including disposal",
                "m2",
                "3200.000",
                "38.00",
                1,
                1,
            ),
            (
                "1.1.2",
                "Dismantling existing brick boundary wall including stacking",
                "m3",
                "42.500",
                "410.00",
                1,
                1,
            ),
            (
                "1.2.1",
                "Excavation in foundation in ordinary soil up to 1.5m depth",
                "m3",
                "2840.000",
                "285.00",
                1,
                2,
            ),
            (
                "1.2.2",
                "Excavation in foundation in ordinary soil exceeding 1.5m depth",
                "m3",
                "960.000",
                "342.00",
                1,
                2,
            ),
            (
                "1.2.3",
                "Excavation in foundation in soft rock without blasting",
                "m3",
                "310.000",
                "486.00",
                1,
                2,
            ),
            (
                "1.2.4",
                "Extra for shoring and strutting to excavated faces",
                "m2",
                "480.000",
                "215.00",
                1,
                2,
            ),
            (
                "1.3.1",
                "Filling in plinth with excavated earth in 200mm layers, watered and rammed",
                "m3",
                "1420.000",
                "195.00",
                2,
                3,
            ),
            (
                "1.3.2",
                "Filling in plinth with approved river sand in 150mm layers",
                "m3",
                "386.000",
                "1180.00",
                2,
                3,
            ),
            (
                "1.3.3",
                "Disposal of surplus excavated earth beyond 50m lead",
                "m3",
                "1680.000",
                "168.00",
                1,
                3,
            ),
            (
                "1.4.1",
                "Anti-termite treatment to foundation trenches and plinth as per IS 6313",
                "m2",
                "1240.000",
                "48.00",
                1,
                2,
            ),
            (
                "1.4.2",
                "Anti-termite treatment to external perimeter after backfilling",
                "Rmt",
                "168.000",
                "92.00",
                2,
                3,
            ),
            (
                "1.5.1",
                "Providing and laying 150mm thick soling of hand-packed rubble",
                "m2",
                "1180.000",
                "268.00",
                1,
                2,
            ),
        ),
    ),
    _group(
        "2",
        "Plain and Reinforced Concrete",
        (
            (
                "2.1.1",
                "Plain cement concrete M10 grade in levelling course below footings",
                "m3",
                "148.000",
                "5850.00",
                1,
                2,
            ),
            (
                "2.1.2",
                "Plain cement concrete M15 grade in plinth beam bedding",
                "m3",
                "62.000",
                "6240.00",
                2,
                2,
            ),
            (
                "2.1.3",
                "Plain cement concrete M10 grade in apron and plinth protection",
                "m3",
                "38.500",
                "5850.00",
                3,
                4,
            ),
            (
                "2.2.1",
                "Reinforced cement concrete M25 grade in isolated and combined footings",
                "m3",
                "486.000",
                "7800.00",
                1,
                2,
            ),
            (
                "2.2.2",
                "Reinforced cement concrete M30 grade in raft foundation",
                "m3",
                "228.000",
                "8450.00",
                1,
                2,
            ),
            (
                "2.2.3",
                "Reinforced cement concrete M25 grade in plinth beams",
                "m3",
                "164.000",
                "7800.00",
                2,
                2,
            ),
            (
                "2.2.4",
                "Reinforced cement concrete M30 grade in columns up to plinth level",
                "m3",
                "118.000",
                "8450.00",
                1,
                2,
            ),
            (
                "2.3.1",
                "Reinforced cement concrete M30 grade in columns above plinth, all floors",
                "m3",
                "392.000",
                "8450.00",
                2,
                4,
            ),
            (
                "2.3.2",
                "Reinforced cement concrete M25 grade in suspended floor slabs, all floors",
                "m3",
                "648.000",
                "7800.00",
                2,
                4,
            ),
            (
                "2.3.3",
                "Reinforced cement concrete M25 grade in beams, all floors",
                "m3",
                "374.000",
                "7800.00",
                2,
                4,
            ),
            (
                "2.3.4",
                "Reinforced cement concrete M25 grade in staircase waist slab and steps",
                "m3",
                "86.500",
                "8120.00",
                2,
                4,
            ),
            (
                "2.3.5",
                "Reinforced cement concrete M25 grade in lift machine room slab",
                "m3",
                "24.000",
                "8120.00",
                4,
                4,
            ),
            (
                "2.4.1",
                "Reinforced cement concrete M25 grade in chajjas and weather sheds",
                "m3",
                "42.800",
                "8340.00",
                3,
                4,
            ),
            (
                "2.4.2",
                "Reinforced cement concrete M25 grade in terrace parapet coping",
                "m3",
                "18.600",
                "8340.00",
                4,
                4,
            ),
            (
                "2.4.3",
                "Reinforced cement concrete M25 grade in overhead water tank walls and slab",
                "m3",
                "56.400",
                "8560.00",
                4,
                4,
            ),
            (
                "2.5.1",
                "Providing and laying 100mm thick RCC M20 floor slab on grade with mesh",
                "m2",
                "1180.000",
                "985.00",
                2,
                3,
            ),
            (
                "2.5.2",
                "Extra for pumping concrete above third floor level",
                "m3",
                "486.000",
                "285.00",
                3,
                4,
            ),
            (
                "2.6.1",
                "Providing construction joints with PVC waterstop 150mm wide",
                "Rmt",
                "142.000",
                "486.00",
                1,
                2,
            ),
            (
                "2.6.2",
                "Curing compound applied to exposed concrete surfaces",
                "m2",
                "4280.000",
                "42.00",
                2,
                4,
            ),
        ),
    ),
    _group(
        "3",
        "Reinforcement Steel",
        (
            (
                "3.1.1",
                "Providing, cutting, bending and fixing Fe500D TMT bars in foundations",
                "MT",
                "68.400",
                "76000.00",
                1,
                2,
            ),
            (
                "3.1.2",
                "Providing, cutting, bending and fixing Fe500D TMT bars in columns",
                "MT",
                "43.000",
                "76000.00",
                2,
                4,
            ),
            (
                "3.1.3",
                "Providing, cutting, bending and fixing Fe500D TMT bars in beams",
                "MT",
                "58.200",
                "76000.00",
                2,
                4,
            ),
            (
                "3.1.4",
                "Providing, cutting, bending and fixing Fe500D TMT bars in slabs",
                "MT",
                "71.600",
                "76000.00",
                2,
                4,
            ),
            (
                "3.1.5",
                "Providing, cutting, bending and fixing Fe500D TMT bars in staircases",
                "MT",
                "12.800",
                "76000.00",
                2,
                4,
            ),
            (
                "3.2.1",
                "Providing and fixing welded steel mesh 6mm at 150mm c/c in floor slab",
                "m2",
                "1180.000",
                "168.00",
                2,
                3,
            ),
            (
                "3.2.2",
                "Providing and fixing MS couplers for bar diameters 20mm and above",
                "Each",
                "486.000",
                "285.00",
                2,
                4,
            ),
            (
                "3.3.1",
                "Providing and fixing cover blocks of approved type",
                "Each",
                "12400.000",
                "6.50",
                1,
                4,
            ),
            (
                "3.3.2",
                "Providing and fixing chairs and spacers fabricated from 12mm bars",
                "MT",
                "3.400",
                "78000.00",
                2,
                4,
            ),
            (
                "3.4.1",
                "Providing and fixing structural steel sections in lift shaft supports",
                "MT",
                "6.800",
                "94000.00",
                4,
                4,
            ),
        ),
    ),
    _group(
        "4",
        "Formwork and Shuttering",
        (
            (
                "4.1.1",
                "Formwork to sides of footings and pile caps",
                "m2",
                "1240.000",
                "312.00",
                1,
                2,
            ),
            ("4.1.2", "Formwork to plinth beams, all faces", "m2", "986.000", "328.00", 2, 2),
            ("4.1.3", "Formwork to columns up to plinth level", "m2", "742.000", "340.00", 1, 2),
            (
                "4.2.1",
                "Formwork to beam sides and soffits, all floors",
                "m2",
                "2860.000",
                "385.00",
                2,
                4,
            ),
            (
                "4.2.2",
                "Formwork to slab soffits including propping, all floors",
                "m2",
                "4180.000",
                "365.00",
                2,
                4,
            ),
            (
                "4.2.3",
                "Formwork to columns above plinth level, all floors",
                "m2",
                "2240.000",
                "340.00",
                2,
                4,
            ),
            (
                "4.2.4",
                "Formwork to staircase waist slab, risers and landings",
                "m2",
                "486.000",
                "412.00",
                2,
                4,
            ),
            (
                "4.3.1",
                "Formwork to chajjas, weather sheds and projections",
                "m2",
                "624.000",
                "448.00",
                3,
                4,
            ),
            ("4.3.2", "Formwork to parapet walls and coping", "m2", "386.000", "398.00", 4, 4),
            (
                "4.3.3",
                "Formwork to overhead water tank walls and soffit",
                "m2",
                "462.000",
                "436.00",
                4,
                4,
            ),
            (
                "4.4.1",
                "Extra for formwork left in position in inaccessible locations",
                "m2",
                "142.000",
                "268.00",
                3,
                4,
            ),
            (
                "4.4.2",
                "Providing and fixing MS props and adjustable jacks, hire per month",
                "Each",
                "1840.000",
                "48.00",
                2,
                4,
            ),
            ("4.5.1", "Formwork to lift shaft walls, both faces", "m2", "684.000", "420.00", 2, 4),
            (
                "4.5.2",
                "Providing chamfer fillets 25mm at all exposed concrete arrises",
                "Rmt",
                "2480.000",
                "38.00",
                2,
                4,
            ),
        ),
    ),
    _group(
        "5",
        "Masonry",
        (
            (
                "5.1.1",
                "Brickwork with common burnt clay bricks 230mm thick in CM 1:6, superstructure",
                "m3",
                "1850.000",
                "6850.00",
                2,
                4,
            ),
            (
                "5.1.2",
                "Brickwork with common burnt clay bricks 230mm thick in CM 1:4, "
                "foundation and plinth",
                "m3",
                "268.000",
                "7120.00",
                1,
                2,
            ),
            (
                "5.1.3",
                "Half brick masonry 115mm thick in CM 1:4 with hoop iron reinforcement",
                "m2",
                "1620.000",
                "985.00",
                3,
                4,
            ),
            (
                "5.2.1",
                "AAC block masonry 200mm thick in approved adhesive mortar",
                "m3",
                "486.000",
                "4950.00",
                3,
                4,
            ),
            (
                "5.2.2",
                "AAC block masonry 100mm thick in approved adhesive mortar",
                "m2",
                "864.000",
                "745.00",
                3,
                4,
            ),
            (
                "5.3.1",
                "Providing and fixing RCC lintels over openings, precast",
                "m3",
                "38.400",
                "8650.00",
                3,
                4,
            ),
            (
                "5.3.2",
                "Providing and laying damp proof course 40mm thick in CM 1:2",
                "m2",
                "312.000",
                "486.00",
                2,
                3,
            ),
            (
                "5.4.1",
                "Providing chicken wire mesh 150mm wide at masonry-concrete junctions",
                "Rmt",
                "2840.000",
                "68.00",
                3,
                4,
            ),
            (
                "5.4.2",
                "Raking out joints in masonry to receive plaster",
                "m2",
                "6480.000",
                "24.00",
                3,
                4,
            ),
            (
                "5.5.1",
                "Stone masonry in random rubble for compound wall foundation",
                "m3",
                "142.000",
                "3860.00",
                3,
                4,
            ),
            (
                "5.5.2",
                "Providing and fixing precast concrete jaali 50mm thick",
                "m2",
                "86.000",
                "1240.00",
                4,
                4,
            ),
            (
                "5.6.1",
                "Building in and making good around pipes, ducts and conduits",
                "Each",
                "486.000",
                "185.00",
                3,
                4,
            ),
        ),
    ),
    _group(
        "6",
        "Plastering and Rendering",
        (
            (
                "6.1.1",
                "Cement plaster 20mm thick in CM 1:4 to external wall surfaces",
                "m2",
                "3480.000",
                "385.00",
                3,
                4,
            ),
            (
                "6.1.2",
                "Cement plaster 15mm thick in CM 1:4 to external soffits and chajjas",
                "m2",
                "624.000",
                "412.00",
                3,
                4,
            ),
            (
                "6.2.1",
                "Cement plaster 12mm thick in CM 1:6 to internal wall surfaces",
                "m2",
                "6480.000",
                "320.00",
                3,
                4,
            ),
            (
                "6.2.2",
                "Cement plaster 6mm thick in CM 1:4 to internal ceiling surfaces",
                "m2",
                "2840.000",
                "285.00",
                3,
                4,
            ),
            (
                "6.2.3",
                "Cement plaster 12mm thick in CM 1:4 to staircase walls and soffits",
                "m2",
                "486.000",
                "348.00",
                3,
                4,
            ),
            (
                "6.3.1",
                "Neeru finish to internal plastered surfaces",
                "m2",
                "6480.000",
                "68.00",
                4,
                4,
            ),
            (
                "6.3.2",
                "Sand-faced textured plaster to external elevation features",
                "m2",
                "486.000",
                "486.00",
                4,
                4,
            ),
            (
                "6.4.1",
                "Providing grooves 12mm x 12mm in external plaster at floor lines",
                "Rmt",
                "1240.000",
                "58.00",
                4,
                4,
            ),
            (
                "6.4.2",
                "Providing drip mould to chajja and sill projections",
                "Rmt",
                "684.000",
                "72.00",
                4,
                4,
            ),
            (
                "6.5.1",
                "Plaster to lift shaft internal walls in CM 1:4",
                "m2",
                "624.000",
                "398.00",
                3,
                4,
            ),
            (
                "6.5.2",
                "Plaster to overhead tank internal surfaces with waterproofing compound",
                "m2",
                "268.000",
                "486.00",
                4,
                4,
            ),
            (
                "6.6.1",
                "Making good plaster after electrical and plumbing chasing",
                "Rmt",
                "3860.000",
                "48.00",
                4,
                4,
            ),
        ),
    ),
    _group(
        "7",
        "Flooring, Dado and Skirting",
        (
            (
                "7.1.1",
                "Providing and laying 40mm thick cement concrete flooring base",
                "m2",
                "2240.000",
                "486.00",
                3,
                4,
            ),
            (
                "7.1.2",
                "Providing and laying ceramic tile flooring 300x300mm in balconies and utility",
                "m2",
                "486.000",
                "842.00",
                4,
                4,
            ),
            (
                "7.1.3",
                "Providing and laying vitrified tile flooring 600x600mm in living and bedrooms",
                "m2",
                "1960.000",
                "1240.00",
                4,
                4,
            ),
            (
                "7.1.4",
                "Providing and laying anti-skid ceramic tile flooring in toilets",
                "m2",
                "342.000",
                "925.00",
                4,
                4,
            ),
            (
                "7.2.1",
                "Providing and laying Kota stone flooring 25mm thick in staircases",
                "m2",
                "486.000",
                "985.00",
                4,
                4,
            ),
            (
                "7.2.2",
                "Providing and laying granite 18mm thick to lift lobby floors",
                "m2",
                "168.000",
                "2860.00",
                4,
                4,
            ),
            (
                "7.2.3",
                "Providing and laying granite 18mm thick to kitchen platform tops",
                "m2",
                "142.000",
                "3240.00",
                4,
                4,
            ),
            (
                "7.3.1",
                "Providing and fixing ceramic tile dado 300x450mm in toilets to 2.1m height",
                "m2",
                "864.000",
                "890.00",
                4,
                4,
            ),
            (
                "7.3.2",
                "Providing and fixing ceramic tile dado in kitchens to 600mm above platform",
                "m2",
                "268.000",
                "890.00",
                4,
                4,
            ),
            (
                "7.4.1",
                "Providing and fixing vitrified tile skirting 100mm high",
                "Rmt",
                "2480.000",
                "268.00",
                4,
                4,
            ),
            (
                "7.4.2",
                "Providing and fixing Kota stone skirting 150mm high to staircases",
                "Rmt",
                "486.000",
                "218.00",
                4,
                4,
            ),
            (
                "7.5.1",
                "Providing and laying IPS flooring 50mm thick in terrace and service areas",
                "m2",
                "684.000",
                "586.00",
                4,
                4,
            ),
            (
                "7.5.2",
                "Providing and laying chequered tile paving in external circulation",
                "m2",
                "486.000",
                "742.00",
                4,
                4,
            ),
            (
                "7.6.1",
                "Providing and fixing nosing tiles to staircase treads",
                "Rmt",
                "342.000",
                "186.00",
                4,
                4,
            ),
            (
                "7.6.2",
                "Providing expansion and control joints in flooring with sealant",
                "Rmt",
                "268.000",
                "324.00",
                4,
                4,
            ),
        ),
    ),
    _group(
        "8",
        "Painting and Protective Finishes",
        (
            (
                "8.1.1",
                "Applying two coats of cement primer to internal plastered surfaces",
                "m2",
                "9320.000",
                "48.00",
                4,
                4,
            ),
            (
                "8.1.2",
                "Applying two coats of acrylic emulsion paint to internal walls and ceilings",
                "m2",
                "9320.000",
                "130.00",
                4,
                4,
            ),
            (
                "8.2.1",
                "Applying one coat primer and two coats exterior emulsion to external walls",
                "m2",
                "3480.000",
                "168.00",
                4,
                4,
            ),
            (
                "8.2.2",
                "Applying textured exterior coating to elevation feature panels",
                "m2",
                "486.000",
                "215.00",
                4,
                4,
            ),
            (
                "8.3.1",
                "Applying two coats synthetic enamel to MS railings and grills",
                "m2",
                "684.000",
                "145.00",
                4,
                4,
            ),
            (
                "8.3.2",
                "Applying two coats synthetic enamel to steel doors and frames",
                "m2",
                "268.000",
                "145.00",
                4,
                4,
            ),
            (
                "8.4.1",
                "Applying French polish to flush door shutters, both faces",
                "m2",
                "486.000",
                "268.00",
                4,
                4,
            ),
            (
                "8.4.2",
                "Applying two coats melamine polish to hardwood frames",
                "Rmt",
                "864.000",
                "142.00",
                4,
                4,
            ),
            (
                "8.5.1",
                "Applying anti-corrosive epoxy primer to embedded steelwork",
                "m2",
                "142.000",
                "218.00",
                3,
                4,
            ),
            (
                "8.5.2",
                "Applying two coats bituminous paint to concrete surfaces in contact with earth",
                "m2",
                "486.000",
                "96.00",
                2,
                3,
            ),
            (
                "8.6.1",
                "Painting identification and signage to services, ducts and shafts",
                "Each",
                "168.000",
                "285.00",
                4,
                4,
            ),
        ),
    ),
    _group(
        "9",
        "Waterproofing and Damp Proofing",
        (
            (
                "9.1.1",
                "Providing and laying APP modified bitumen membrane 3mm to terrace",
                "m2",
                "1180.000",
                "745.00",
                3,
                4,
            ),
            (
                "9.1.2",
                "Providing and laying brick bat coba waterproofing to terrace with slope",
                "m2",
                "1180.000",
                "620.00",
                3,
                4,
            ),
            (
                "9.2.1",
                "Providing box-type waterproofing to toilet sunk slabs",
                "m2",
                "342.000",
                "886.00",
                3,
                4,
            ),
            (
                "9.2.2",
                "Providing chemical waterproofing to overhead and underground tanks",
                "m2",
                "486.000",
                "748.00",
                4,
                4,
            ),
            (
                "9.3.1",
                "Providing crystalline waterproofing admixture to foundation concrete",
                "m3",
                "486.000",
                "386.00",
                1,
                2,
            ),
            (
                "9.3.2",
                "Providing and applying two coats cementitious waterproof coating to "
                "basement walls",
                "m2",
                "624.000",
                "486.00",
                2,
                3,
            ),
            (
                "9.4.1",
                "Providing and fixing PVC water bar 230mm at construction joints",
                "Rmt",
                "268.000",
                "486.00",
                2,
                3,
            ),
            (
                "9.4.2",
                "Providing and fixing aluminium water bar at door thresholds of wet areas",
                "Rmt",
                "186.000",
                "312.00",
                4,
                4,
            ),
            (
                "9.5.1",
                "Providing and fixing polyethylene sheet 200 micron below floor slab",
                "m2",
                "1180.000",
                "68.00",
                2,
                3,
            ),
        ),
    ),
    _group(
        "10",
        "Doors, Windows and Joinery",
        (
            (
                "10.1.1",
                "Providing and fixing hardwood door frames 100x63mm section",
                "Rmt",
                "864.000",
                "486.00",
                4,
                4,
            ),
            (
                "10.1.2",
                "Providing and fixing flush door shutters 32mm thick, both faces commercial ply",
                "Each",
                "168.000",
                "3850.00",
                4,
                4,
            ),
            (
                "10.1.3",
                "Providing and fixing FRP door shutters 30mm thick to toilets",
                "Each",
                "86.000",
                "3240.00",
                4,
                4,
            ),
            (
                "10.1.4",
                "Providing and fixing main entrance door with teak veneer both faces",
                "Each",
                "42.000",
                "12400.00",
                4,
                4,
            ),
            (
                "10.2.1",
                "Providing and fixing aluminium sliding windows with 5mm float glass",
                "m2",
                "486.000",
                "5600.00",
                4,
                4,
            ),
            (
                "10.2.2",
                "Providing and fixing aluminium ventilators with louvres and mesh",
                "m2",
                "142.000",
                "4860.00",
                4,
                4,
            ),
            (
                "10.2.3",
                "Providing and fixing UPVC sliding windows to bedrooms",
                "m2",
                "268.000",
                "6240.00",
                4,
                4,
            ),
            (
                "10.3.1",
                "Providing and fixing MS grills to windows, 12mm square bars",
                "m2",
                "486.000",
                "1680.00",
                4,
                4,
            ),
            (
                "10.3.2",
                "Providing and fixing MS handrail to staircase, 50mm dia pipe",
                "Rmt",
                "186.000",
                "1450.00",
                4,
                4,
            ),
            (
                "10.3.3",
                "Providing and fixing SS balustrade with glass infill to balconies",
                "Rmt",
                "268.000",
                "4860.00",
                4,
                4,
            ),
            (
                "10.4.1",
                "Providing and fixing door hardware set including hinges, lock and stopper",
                "Each",
                "296.000",
                "1240.00",
                4,
                4,
            ),
            (
                "10.4.2",
                "Providing and fixing door closers to common area doors",
                "Each",
                "42.000",
                "2860.00",
                4,
                4,
            ),
            (
                "10.5.1",
                "Providing and fixing rolling shutter to generator and pump rooms",
                "m2",
                "38.000",
                "3860.00",
                4,
                4,
            ),
            (
                "10.5.2",
                "Providing and fixing fire-rated door assembly to lift lobby, 2 hour rating",
                "Each",
                "10.000",
                "28400.00",
                4,
                4,
            ),
        ),
    ),
    _group(
        "11",
        "Sanitary and Plumbing",
        (
            (
                "11.1.1",
                "Providing and fixing wall-hung EWC with concealed cistern and seat cover",
                "Each",
                "126.000",
                "12400.00",
                4,
                4,
            ),
            (
                "11.1.2",
                "Providing and fixing wash basin 550x400mm with pedestal and fittings",
                "Each",
                "126.000",
                "4860.00",
                4,
                4,
            ),
            (
                "11.1.3",
                "Providing and fixing stainless steel kitchen sink with drainboard",
                "Each",
                "42.000",
                "5240.00",
                4,
                4,
            ),
            (
                "11.2.1",
                "Providing and fixing CP brass diverter with overhead shower arm and rose",
                "Each",
                "126.000",
                "3860.00",
                4,
                4,
            ),
            (
                "11.2.2",
                "Providing and fixing CP brass pillar cock to basins",
                "Each",
                "168.000",
                "1240.00",
                4,
                4,
            ),
            (
                "11.2.3",
                "Providing and fixing CP brass angle valve with flexible connection",
                "Each",
                "420.000",
                "486.00",
                4,
                4,
            ),
            (
                "11.3.1",
                "Providing and laying CPVC pipe 25mm dia concealed in walls with fittings",
                "Rmt",
                "1240.000",
                "386.00",
                3,
                4,
            ),
            (
                "11.3.2",
                "Providing and laying CPVC pipe 15mm dia concealed in walls with fittings",
                "Rmt",
                "1860.000",
                "268.00",
                3,
                4,
            ),
            (
                "11.4.1",
                "Providing and laying UPVC soil pipe 110mm dia with fittings and clamps",
                "Rmt",
                "684.000",
                "486.00",
                3,
                4,
            ),
            (
                "11.4.2",
                "Providing and laying UPVC waste pipe 75mm dia with fittings and clamps",
                "Rmt",
                "486.000",
                "342.00",
                3,
                4,
            ),
            (
                "11.4.3",
                "Providing and fixing floor trap with stainless steel grating",
                "Each",
                "210.000",
                "486.00",
                4,
                4,
            ),
            (
                "11.5.1",
                "Providing and constructing brick masonry inspection chamber 600x450mm",
                "Each",
                "24.000",
                "8640.00",
                3,
                4,
            ),
            (
                "11.5.2",
                "Providing and laying RCC NP2 pipe 150mm dia for external drainage",
                "Rmt",
                "268.000",
                "742.00",
                3,
                4,
            ),
            (
                "11.6.1",
                "Providing and fixing PVC rainwater downtake pipe 110mm dia with fittings",
                "Rmt",
                "486.000",
                "386.00",
                4,
                4,
            ),
            (
                "11.6.2",
                "Providing and fixing terrace rainwater khurra with grating",
                "Each",
                "38.000",
                "1240.00",
                4,
                4,
            ),
        ),
    ),
)


def items() -> tuple[BoqItem, ...]:
    """Every priced item, in bill order."""
    return tuple(item for group in CATALOGUE for item in group.items)


def item_by_number(number: str) -> BoqItem:
    """One item, by its bill number. Raises rather than returning ``None``.

    A defect specification naming an item that does not exist is a defect in the specification, and
    it must stop the generator rather than silently plant nothing.
    """
    for item in items():
        if item.number == number:
            return item
    raise KeyError(f"no catalogue item numbered {number!r}")


def contract_value() -> Decimal:
    """The bill's own total, which every generated document must reconcile to."""
    return sum((item.amount for item in items()), start=Decimal("0.00"))
