"""Writing the bundle as spreadsheets, reproducibly.

The reproducibility machinery is lifted from ``scripts/generate_synthetic_project.py``, where it
cost three attempts to get right, and the reasoning is worth repeating because it is not obvious:
an XLSX is a ZIP archive, openpyxl stamps the clock into both the archive entries and
``docProps/core.xml``, and in a content-addressed store a changed byte is a *new document*. A
generator that is not byte-stable silently duplicates the corpus every time anyone runs it.

Column headers are spelled to match the aliases in ``aedifex.extraction.spreadsheet``. That is a
real tension with the benchmark's purpose and it is worth naming rather than hiding: writing headers
the reader already knows means the spreadsheet path tests the *rules* and not the *reader*. The
reader is tested by the PDF path in :mod:`scripts.synthetic.render`, where the layout is what a
printed bill looks like and the reader gets no such help.
"""

from __future__ import annotations

import re
import zipfile
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from typing import Final

from openpyxl import Workbook
from openpyxl.worksheet.worksheet import Worksheet

from scripts.synthetic.bundle import Bundle
from scripts.synthetic.spec import (
    CONSULTANT,
    CONTRACTOR,
    EMPLOYER,
    PERIODS,
    PROJECT_NAME,
    PROJECT_REF,
)

__all__ = ["BANNER", "write_workbooks"]

BANNER: Final[str] = (
    "SYNTHETIC DATA - generated by Aedifex for benchmarking. Fictional project, no real parties, "
    "no real prices. Not evidence of anything about real documents."
)

GENERATED_AT: Final[datetime] = datetime(2026, 8, 30, tzinfo=UTC)
ZIP_TIMESTAMP: Final[tuple[int, int, int, int, int, int]] = (2026, 8, 30, 0, 0, 0)

_MODIFIED_ELEMENT: Final[re.Pattern[bytes]] = re.compile(
    rb"(<dcterms:modified[^>]*>)[^<]*(</dcterms:modified>)"
)
_PINNED_STAMP: Final[bytes] = GENERATED_AT.strftime("%Y-%m-%dT%H:%M:%SZ").encode("ascii")


def _normalise_part(filename: str, payload: bytes) -> bytes:
    if filename != "docProps/core.xml":
        return payload
    return _MODIFIED_ELEMENT.sub(rb"\g<1>" + _PINNED_STAMP + rb"\g<2>", payload)


def _rewrite_archive_deterministically(path: Path) -> None:
    with zipfile.ZipFile(path) as source:
        entries = [
            (
                info.filename,
                info.external_attr,
                _normalise_part(info.filename, source.read(info.filename)),
            )
            for info in sorted(source.infolist(), key=lambda item: item.filename)
        ]
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as target:
        for filename, external_attr, payload in entries:
            info = zipfile.ZipInfo(filename, date_time=ZIP_TIMESTAMP)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = external_attr
            target.writestr(info, payload)


def _sheet(workbook: Workbook, title: str, subtitle: str) -> Worksheet:
    workbook.properties.created = GENERATED_AT
    workbook.properties.modified = GENERATED_AT
    workbook.properties.creator = "aedifex-synthetic-generator"
    workbook.properties.lastModifiedBy = "aedifex-synthetic-generator"
    sheet = workbook.active
    if not isinstance(sheet, Worksheet):  # pragma: no cover - a new Workbook always has one
        raise TypeError("a new workbook unexpectedly has no active worksheet")
    sheet.title = title
    sheet.append([BANNER])
    sheet.append([f"Project: {PROJECT_REF}"])
    sheet.append([PROJECT_NAME])
    sheet.append([f"Employer: {EMPLOYER}"])
    sheet.append([f"Contractor: {CONTRACTOR}"])
    sheet.append([subtitle])
    sheet.append([])
    return sheet


def _save(workbook: Workbook, path: Path) -> None:
    workbook.save(path)
    _rewrite_archive_deterministically(path)


def _f(value: Decimal) -> float:
    """Spreadsheets hold numbers, not strings, because a reviewer will sort and total these."""
    return float(value)


def _write_boq(bundle: Bundle, path: Path, revision: str) -> None:
    rows = bundle.boq_rev1 if revision == "Rev01" else bundle.boq_rev2
    workbook = Workbook()
    sheet = _sheet(workbook, "BOQ", f"Bill of Quantities — {revision}")
    sheet.append(["Item No", "Description", "Unit", "Quantity", "Rate", "Amount"])
    total = Decimal("0.00")
    for item in rows:
        sheet.append(
            [
                item.number,
                item.description,
                item.unit,
                _f(item.quantity),
                _f(item.rate),
                _f(item.amount),
            ]
        )
        total += item.amount
    sheet.append([])
    sheet.append(["", "Total", "", "", "", _f(total)])
    _save(workbook, path)


def _write_measurement(bundle: Bundle, path: Path, period: int) -> None:
    detail = next(one for one in PERIODS if one.number == period)
    workbook = Workbook()
    sheet = _sheet(
        workbook,
        "Measurement",
        f"Measurement sheet for period {period}, measured on {detail.measured_on}",
    )
    sheet.append(["Item No", "Description", "Unit", "Measured Quantity"])
    for row in bundle.measurements[period]:
        sheet.append(
            [
                row.item.number,
                row.item.description,
                row.item.unit,
                _f(row.measured_quantity),
            ]
        )
    _save(workbook, path)


def _write_bill(bundle: Bundle, path: Path, period: int) -> None:
    detail = next(one for one in PERIODS if one.number == period)
    workbook = Workbook()
    sheet = _sheet(
        workbook,
        "RA Bill",
        f"Running Account Bill {detail.label}, dated {detail.billed_on}",
    )
    sheet.append(
        [
            "Item No",
            "Description",
            "Unit",
            "Previous Certified Quantity",
            "Current Claim Quantity",
            "Cumulative Claim Quantity",
            "Rate",
            "Amount",
        ]
    )
    for row in bundle.bills[period]:
        sheet.append(
            [
                row.item.number,
                row.item.description,
                row.item.unit,
                _f(row.previous_certified),
                _f(row.current_claim),
                _f(row.cumulative_claim),
                _f(row.claimed_rate),
                _f(row.amount),
            ]
        )
    # Unparented claims sit in the bill exactly as they would on a real one: below the scheduled
    # items, with no marker distinguishing the authorised from the unauthorised. Labelling them
    # would hand the answer to any future rule and destroy the SYN-D08 / SYN-D09 pair.
    for extra in bundle.extras.get(period, ()):
        sheet.append(
            [
                extra.number,
                extra.description,
                extra.unit,
                0,
                _f(extra.quantity),
                _f(extra.quantity),
                _f(extra.rate),
                _f(extra.amount),
            ]
        )
    sheet.append([])
    sheet.append(["", "Total", "", "", "", "", "", _f(bundle.stated_bill_totals[period])])
    _save(workbook, path)


def _write_variations(bundle: Bundle, path: Path) -> None:
    workbook = Workbook()
    sheet = _sheet(workbook, "Variations", "Approved variation orders")
    sheet.append(["Item No", "Description", "Unit", "Quantity", "Rate", "Amount"])
    for order in bundle.variations:
        sheet.append(
            [
                order.reference,
                order.description,
                order.unit,
                _f(order.quantity),
                _f(order.rate),
                _f(order.amount),
            ]
        )
    sheet.append([])
    sheet.append([f"Approved by: {order.approved_by} on {order.dated}"])
    sheet.append([f"Consultant of record: {CONSULTANT}"])
    _save(workbook, path)


def write_workbooks(bundle: Bundle, directory: Path) -> list[Path]:
    """Write every spreadsheet. Returns the paths, in bill order."""
    directory.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    for revision in ("Rev01", "Rev02"):
        path = directory / f"SYNTHETIC_BOQ-{revision}_{PROJECT_REF}.xlsx"
        _write_boq(bundle, path, revision)
        written.append(path)

    for period in sorted(bundle.measurements):
        path = directory / f"SYNTHETIC_Measurement-{period:02d}_{PROJECT_REF}.xlsx"
        _write_measurement(bundle, path, period)
        written.append(path)

    for period in sorted(bundle.bills):
        path = directory / f"SYNTHETIC_RA-Bill-{period:02d}_{PROJECT_REF}.xlsx"
        _write_bill(bundle, path, period)
        written.append(path)

    path = directory / f"SYNTHETIC_Variation-Orders_{PROJECT_REF}.xlsx"
    _write_variations(bundle, path)
    written.append(path)

    return written
