"""add derived facts and project chronology

Revision ID: da09a68e4233
Revises: 31ee35a5a943
Created: 2026-08-20 04:14:38.813297+00:00

Downgrade must be implemented and must be tested. A migration that cannot be reversed is a
migration that cannot be safely deployed.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "da09a68e4233"
down_revision: str | None = "31ee35a5a943"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "derived_facts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=True),
        sa.Column("fact_type", sa.String(length=64), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "money",
                "quantity",
                "percentage",
                "date",
                "duration",
                "identifier",
                "company",
                "location",
                "document_reference",
                "text",
                name="factkind",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("numeric_value", sa.Numeric(precision=28, scale=10), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("unit", sa.String(length=32), nullable=True),
        sa.Column("calculation", sa.String(length=128), nullable=False),
        sa.Column("calculation_version", sa.String(length=32), nullable=False),
        sa.Column("produced_by", sa.String(length=128), nullable=False),
        sa.Column("expression", sa.Text(), nullable=False),
        sa.Column(
            "computed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(document_id IS NULL) <> (project_id IS NULL)",
            name=op.f("ck_derived_facts_derived_fact_scoped_to_exactly_one_subject"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_derived_facts_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_derived_facts_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_derived_facts")),
    )
    op.create_index(
        op.f("ix_derived_facts_document_id"), "derived_facts", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_derived_facts_fact_type"), "derived_facts", ["fact_type"], unique=False
    )
    op.create_index(
        op.f("ix_derived_facts_project_id"), "derived_facts", ["project_id"], unique=False
    )
    op.create_index(
        "uq_derived_facts_document",
        "derived_facts",
        ["document_id", "fact_type", "calculation_version"],
        unique=True,
        postgresql_where=sa.text("document_id IS NOT NULL"),
    )
    op.create_index(
        "uq_derived_facts_project",
        "derived_facts",
        ["project_id", "fact_type", "calculation_version"],
        unique=True,
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.create_table(
        "derived_fact_inputs",
        sa.Column("derived_fact_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("fact_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["derived_fact_id"],
            ["derived_facts.id"],
            name=op.f("fk_derived_fact_inputs_derived_fact_id_derived_facts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["extracted_facts.id"],
            name=op.f("fk_derived_fact_inputs_fact_id_extracted_facts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("derived_fact_id", "role", name=op.f("pk_derived_fact_inputs")),
    )
    op.add_column("extracted_facts", sa.Column("date_value", sa.Date(), nullable=True))
    # The primary key moves from (finding_id, fact_id) to (finding_id, role). Autogenerate does not
    # detect primary-key changes, so this is written by hand: without it the model and the database
    # would disagree silently, and a rule citing one fact in two roles would violate the old key.
    op.drop_constraint(op.f("pk_finding_evidence"), "finding_evidence", type_="primary")
    op.create_primary_key(op.f("pk_finding_evidence"), "finding_evidence", ["finding_id", "role"])
    op.add_column("finding_evidence", sa.Column("derived_fact_id", sa.Uuid(), nullable=True))
    op.alter_column("finding_evidence", "fact_id", existing_type=sa.UUID(), nullable=True)
    op.create_foreign_key(
        op.f("fk_finding_evidence_derived_fact_id_derived_facts"),
        "finding_evidence",
        "derived_facts",
        ["derived_fact_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        op.f("ck_finding_evidence_evidence_cites_exactly_one_kind_of_fact"),
        "finding_evidence",
        "(fact_id IS NULL) <> (derived_fact_id IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Evidence rows citing a derived fact cannot exist in the previous schema, which requires every
    # row to name an extracted fact. They are removed before fact_id is made NOT NULL again.
    #
    # The same class of defect as the previous migration's downgrade, caught the same way -- by
    # reversing it against real data rather than by reading it. An evidence link is derived and
    # rebuilt by re-running the analysis; no artifact, provenance row, or extracted fact is touched.
    op.execute("DELETE FROM finding_evidence WHERE derived_fact_id IS NOT NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_finding_evidence_evidence_cites_exactly_one_kind_of_fact"),
        "finding_evidence",
        type_="check",
    )
    op.drop_constraint(
        op.f("fk_finding_evidence_derived_fact_id_derived_facts"),
        "finding_evidence",
        type_="foreignkey",
    )
    op.alter_column("finding_evidence", "fact_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("finding_evidence", "derived_fact_id")
    op.drop_constraint(op.f("pk_finding_evidence"), "finding_evidence", type_="primary")
    op.create_primary_key(
        op.f("pk_finding_evidence"), "finding_evidence", ["finding_id", "fact_id"]
    )
    op.drop_column("extracted_facts", "date_value")
    op.drop_table("derived_fact_inputs")
    op.drop_index(
        "uq_derived_facts_project",
        table_name="derived_facts",
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_derived_facts_document",
        table_name="derived_facts",
        postgresql_where=sa.text("document_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_derived_facts_project_id"), table_name="derived_facts")
    op.drop_index(op.f("ix_derived_facts_fact_type"), table_name="derived_facts")
    op.drop_index(op.f("ix_derived_facts_document_id"), table_name="derived_facts")
    op.drop_table("derived_facts")
    # ### end Alembic commands ###
