"""add policy provisions and provision evidence

Revision ID: 0521215d5cb9
Revises: a32fb2774ec9
Created: 2026-08-21 01:38:48.010255+00:00

Downgrade must be implemented and must be tested. A migration that cannot be reversed is a
migration that cannot be safely deployed.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0521215d5cb9"
down_revision: str | None = "a32fb2774ec9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "policy_provisions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("provision_type", sa.String(length=64), nullable=False),
        sa.Column("clause", sa.String(length=64), nullable=False),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("span_start", sa.Integer(), nullable=False),
        sa.Column("span_end", sa.Integer(), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("authority", sa.String(length=64), nullable=False),
        sa.Column("jurisdiction", sa.String(length=8), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=True),
        sa.Column("applies_to", sa.String(length=64), nullable=False),
        sa.Column("applies_from", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("applies_to_max", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("share", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("cap_amount", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("extractor", sa.String(length=64), nullable=False),
        sa.Column("extractor_version", sa.String(length=32), nullable=False),
        sa.Column(
            "extracted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "applies_from IS NULL OR applies_to_max IS NULL OR applies_to_max >= applies_from",
            name=op.f("ck_policy_provisions_band_is_whole"),
        ),
        sa.CheckConstraint(
            "currency IS NULL OR currency = upper(currency)",
            name=op.f("ck_policy_provisions_currency_is_upper"),
        ),
        sa.CheckConstraint("page >= 1", name=op.f("ck_policy_provisions_page_is_one_based")),
        sa.CheckConstraint(
            "share IS NOT NULL OR cap_amount IS NOT NULL",
            name=op.f("ck_policy_provisions_imposes_something"),
        ),
        sa.CheckConstraint(
            "span_end >= span_start", name=op.f("ck_policy_provisions_span_is_whole")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_policy_provisions_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_provisions")),
        sa.UniqueConstraint(
            "document_id",
            "provision_type",
            "clause",
            "extractor_version",
            name="one_provision_per_clause_per_extractor_version",
        ),
    )
    op.create_index(
        op.f("ix_policy_provisions_authority"), "policy_provisions", ["authority"], unique=False
    )
    op.create_index(
        op.f("ix_policy_provisions_document_id"), "policy_provisions", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_policy_provisions_provision_type"),
        "policy_provisions",
        ["provision_type"],
        unique=False,
    )
    op.add_column("derived_fact_inputs", sa.Column("provision_id", sa.Uuid(), nullable=True))
    op.alter_column("derived_fact_inputs", "fact_id", existing_type=sa.UUID(), nullable=True)
    op.create_foreign_key(
        op.f("fk_derived_fact_inputs_provision_id_policy_provisions"),
        "derived_fact_inputs",
        "policy_provisions",
        ["provision_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_check_constraint(
        op.f("ck_derived_fact_inputs_input_is_fact_or_provision"),
        "derived_fact_inputs",
        "(fact_id IS NULL) <> (provision_id IS NULL)",
    )
    op.add_column("finding_evidence", sa.Column("provision_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_finding_evidence_provision_id_policy_provisions"),
        "finding_evidence",
        "policy_provisions",
        ["provision_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###

    # Hand-written, because autogenerate cannot see it: Alembic compares check constraints by NAME,
    # and this one keeps its name while changing meaning. It went from "exactly one of fact or
    # derived fact" to "exactly one of three", and without this the database would keep rejecting
    # every provision citation while the models claimed to allow them. This is the fourth time in
    # this project's history that a same-named constraint change has had to be written by hand.
    op.drop_constraint(
        op.f("ck_finding_evidence_evidence_cites_exactly_one_kind_of_fact"),
        "finding_evidence",
        type_="check",
    )
    # The full final name, via op.f(). A bare name does NOT get the naming convention applied here:
    # a migration op has no table metadata to read the convention from, so it is used verbatim and
    # the constraint lands without the ck_finding_evidence_ prefix the models expect. Caught by the
    # offline DDL harness in tests, which `alembic check` cannot substitute for -- it compares a
    # live database, and the live database had already been repaired by hand.
    op.create_check_constraint(
        op.f("ck_finding_evidence_evidence_cites_exactly_one_kind_of_fact"),
        "finding_evidence",
        "(fact_id IS NOT NULL)::int + (derived_fact_id IS NOT NULL)::int "
        "+ (provision_id IS NOT NULL)::int = 1",
    )


def downgrade() -> None:
    # Reverse the hand-written constraint change first, and drop the rows the old rule cannot hold.
    # A finding that cites a provision has no representation under a two-way check, so those
    # citations go before it is restored. Sound because they are derived evidence, rebuilt by
    # re-running the analysis: no raw document, no provenance row, and no extracted fact is touched.
    op.execute("DELETE FROM finding_evidence WHERE provision_id IS NOT NULL")
    op.drop_constraint(
        op.f("ck_finding_evidence_evidence_cites_exactly_one_kind_of_fact"),
        "finding_evidence",
        type_="check",
    )
    op.create_check_constraint(
        op.f("ck_finding_evidence_evidence_cites_exactly_one_kind_of_fact"),
        "finding_evidence",
        "(fact_id IS NULL) <> (derived_fact_id IS NULL)",
    )

    # Likewise for calculation inputs: fact_id becomes NOT NULL again, so an input that applied a
    # provision rather than reading a fact cannot survive. The derived facts built from them go too
    # -- derived_fact_inputs holds ON DELETE RESTRICT on the fact deliberately, and a computed value
    # must not outlive its inputs.
    # Order matters and the constraints enforce it, which is how this got caught: the derived value
    # is also cited by a finding under ON DELETE RESTRICT, so it cannot go before that citation
    # does. Deliberate -- a computed number must not outlive the evidence chain that explains it.
    op.execute("""
        DELETE FROM finding_evidence WHERE derived_fact_id IN (
            SELECT derived_fact_id FROM derived_fact_inputs WHERE provision_id IS NOT NULL
        )
        """)
    op.execute("""
        DELETE FROM derived_facts WHERE id IN (
            SELECT derived_fact_id FROM derived_fact_inputs WHERE provision_id IS NOT NULL
        )
        """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_finding_evidence_provision_id_policy_provisions"),
        "finding_evidence",
        type_="foreignkey",
    )
    op.drop_column("finding_evidence", "provision_id")
    op.drop_constraint(
        op.f("ck_derived_fact_inputs_input_is_fact_or_provision"),
        "derived_fact_inputs",
        type_="check",
    )
    op.drop_constraint(
        op.f("fk_derived_fact_inputs_provision_id_policy_provisions"),
        "derived_fact_inputs",
        type_="foreignkey",
    )
    op.alter_column("derived_fact_inputs", "fact_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("derived_fact_inputs", "provision_id")
    op.drop_index(op.f("ix_policy_provisions_provision_type"), table_name="policy_provisions")
    op.drop_index(op.f("ix_policy_provisions_document_id"), table_name="policy_provisions")
    op.drop_index(op.f("ix_policy_provisions_authority"), table_name="policy_provisions")
    op.drop_table("policy_provisions")
    # ### end Alembic commands ###
