"""add projects relationships and fact kinds

Revision ID: 31ee35a5a943
Revises: 486135f46988
Created: 2026-08-20 03:52:43.939931+00:00

Downgrade must be implemented and must be tested. A migration that cannot be reversed is a
migration that cannot be safely deployed.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "31ee35a5a943"
down_revision: str | None = "486135f46988"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("external_ref", sa.String(length=256), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("established_by", sa.String(length=128), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint("source_id", "external_ref", name="one_project_per_source_reference"),
    )
    op.create_index(op.f("ix_projects_source_id"), "projects", ["source_id"], unique=False)
    op.create_table(
        "document_relationships",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("from_document_id", sa.Uuid(), nullable=False),
        sa.Column("to_document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "relationship_type",
            sa.Enum(
                "same_tender",
                "amends",
                "supersedes",
                "invites_bids_for",
                "awards",
                "prices",
                "measures",
                "claims_against",
                "certifies",
                "references",
                name="relationshiptype",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("established_by", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_document_id <> to_document_id",
            name=op.f("ck_document_relationships_relationship_joins_two_documents"),
        ),
        sa.ForeignKeyConstraint(
            ["from_document_id"],
            ["documents.id"],
            name=op.f("fk_document_relationships_from_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_document_relationships_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_document_id"],
            ["documents.id"],
            name=op.f("fk_document_relationships_to_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_relationships")),
        sa.UniqueConstraint(
            "from_document_id",
            "to_document_id",
            "relationship_type",
            name="one_relationship_per_pair_and_type",
        ),
    )
    op.create_index(
        op.f("ix_document_relationships_project_id"),
        "document_relationships",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "project_documents",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "tender_notice",
                "bid_document",
                "contract",
                "bill_of_quantities",
                "measurement_book",
                "running_bill",
                "invoice",
                "payment_certificate",
                "inspection_report",
                "completion_certificate",
                "corrigendum",
                "unclassified",
                name="documentrole",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("established_by", sa.String(length=128), nullable=False),
        sa.Column(
            "linked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_project_documents_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_documents_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("project_id", "document_id", name=op.f("pk_project_documents")),
    )
    op.add_column(
        "extracted_facts",
        sa.Column(
            "kind",
            sa.Enum(
                "money",
                "quantity",
                "percentage",
                "date",
                "duration",
                "identifier",
                "company",
                "location",
                "document_reference",
                "text",
                name="factkind",
                native_enum=False,
                length=24,
            ),
            nullable=False,
            # Existing rows predate the shared fact model and cannot be classified retroactively
            # without re-extracting them, so they take the neutral kind. Without this default the
            # ALTER fails outright on a populated table.
            server_default="text",
        ),
    )
    op.create_index(op.f("ix_extracted_facts_kind"), "extracted_facts", ["kind"], unique=False)
    op.add_column("findings", sa.Column("project_id", sa.Uuid(), nullable=True))
    op.alter_column("findings", "document_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("one_finding_per_rule_version"), "findings", type_="unique")
    op.create_index(op.f("ix_findings_project_id"), "findings", ["project_id"], unique=False)
    op.create_index(
        "uq_findings_document_rule",
        "findings",
        ["document_id", "rule_id", "rule_version"],
        unique=True,
        postgresql_where=sa.text("document_id IS NOT NULL"),
    )
    op.create_index(
        "uq_findings_project_rule",
        "findings",
        ["project_id", "rule_id", "rule_version"],
        unique=True,
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.create_foreign_key(
        op.f("fk_findings_project_id_projects"),
        "findings",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_check_constraint(
        op.f("ck_findings_finding_scoped_to_exactly_one_subject"),
        "findings",
        "(document_id IS NULL) <> (project_id IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Project-scoped findings have no representation in the previous schema: it requires every
    # finding to belong to exactly one document, and a cross-document finding belongs to neither of
    # its documents alone. So they are deleted before the NOT NULL is restored.
    #
    # Found by reversing the migration against real data rather than by reading it: the generated
    # downgrade failed with NotNullViolation the moment one project finding existed, which would
    # have made this irreversible in exactly the situation where reversing it matters.
    #
    # Deleting them is sound because a finding is *derived* evidence, reproducible by re-running
    # the analysis over facts that are themselves untouched here. No raw artifact, no provenance
    # row and no extracted fact is removed. Their finding_evidence rows follow via ON DELETE
    # CASCADE.
    op.execute("DELETE FROM findings WHERE project_id IS NOT NULL")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_findings_finding_scoped_to_exactly_one_subject"), "findings", type_="check"
    )
    op.drop_constraint(op.f("fk_findings_project_id_projects"), "findings", type_="foreignkey")
    op.drop_index(
        "uq_findings_project_rule",
        table_name="findings",
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.drop_index(
        "uq_findings_document_rule",
        table_name="findings",
        postgresql_where=sa.text("document_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_findings_project_id"), table_name="findings")
    op.create_unique_constraint(
        op.f("one_finding_per_rule_version"),
        "findings",
        ["document_id", "rule_id", "rule_version"],
        postgresql_nulls_not_distinct=False,
    )
    op.alter_column("findings", "document_id", existing_type=sa.UUID(), nullable=False)
    op.drop_column("findings", "project_id")
    op.drop_index(op.f("ix_extracted_facts_kind"), table_name="extracted_facts")
    op.drop_column("extracted_facts", "kind")
    op.drop_table("project_documents")
    op.drop_index(op.f("ix_document_relationships_project_id"), table_name="document_relationships")
    op.drop_table("document_relationships")
    op.drop_index(op.f("ix_projects_source_id"), table_name="projects")
    op.drop_table("projects")
    # ### end Alembic commands ###
