"""add document version state and derived fact fingerprints

Revision ID: a32fb2774ec9
Revises: 3ba3e533dba4
Created: 2026-08-20 19:09:38.195865+00:00

Downgrade must be implemented and must be tested. A migration that cannot be reversed is a
migration that cannot be safely deployed.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a32fb2774ec9"
down_revision: str | None = "3ba3e533dba4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "derived_facts",
        sa.Column(
            "inputs_fingerprint", sa.String(length=64), server_default=sa.text("''"), nullable=False
        ),
    )
    op.add_column(
        "documents",
        sa.Column(
            "version_state",
            sa.Enum(
                "active",
                "superseded",
                "retired",
                "unknown",
                name="documentversionstate",
                native_enum=False,
                length=16,
            ),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
    )
    op.add_column("documents", sa.Column("version_state_reason", sa.Text(), nullable=True))
    op.create_index(
        op.f("ix_documents_version_state"), "documents", ["version_state"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_version_state"), table_name="documents")
    op.drop_column("documents", "version_state_reason")
    op.drop_column("documents", "version_state")
    op.drop_column("derived_facts", "inputs_fingerprint")
    # ### end Alembic commands ###
