"""fact retractions: withdraw a fact without deleting it

Revision ID: 6a234e15dd11
Revises: 0521215d5cb9
Created: 2026-08-21 04:09:15.158607+00:00

One table, so that an extractor version can say "the fact recorded earlier should not exist"
without deleting it.

Extractor versioning already supersedes a *corrected* fact: a newer version writes a better value
and selection prefers it. A *retraction* writes nothing, so the false row stays newest and stays
selected. Six real facts sat in that state on 2026-08-21 — three CAG audit reports whose narrative
about other people's projects became their own estimated cost, and two model concession agreements
dated from a specimen form — and the facts API was serving all six.

Deleting them was rejected: a finding computed from a fact must remain explainable against the
fact that produced it, so history is not negotiable. The retraction is therefore a new,
append-only row that points at the fact, names the extractor version that withdrew it, and says why.

Downgrade drops the table, which loses the retractions and restores the previous ambiguity. That is
the honest reversal — the false facts themselves are untouched by both directions, because this
migration never writes to ``extracted_facts``.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6a234e15dd11"
down_revision: str | None = "0521215d5cb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fact_retractions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("fact_id", sa.Uuid(), nullable=False),
        sa.Column("retracted_by_extractor", sa.String(length=64), nullable=False),
        sa.Column("retracted_by_version", sa.String(length=32), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "retracted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("software_version", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "length(btrim(reason)) > 0", name=op.f("ck_fact_retractions_reason_is_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["extracted_facts.id"],
            name=op.f("fk_fact_retractions_fact_id_extracted_facts"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fact_retractions")),
        sa.UniqueConstraint("fact_id", name="one_retraction_per_fact"),
    )
    op.create_index(
        op.f("ix_fact_retractions_fact_id"), "fact_retractions", ["fact_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fact_retractions_fact_id"), table_name="fact_retractions")
    op.drop_table("fact_retractions")
    # ### end Alembic commands ###
