"""add extracted facts and findings

Revision ID: 486135f46988
Revises: 34a42436bb53
Created: 2026-08-20 02:43:40.991884+00:00

Downgrade must be implemented and must be tested. A migration that cannot be reversed is a
migration that cannot be safely deployed.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "486135f46988"
down_revision: str | None = "34a42436bb53"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "extracted_facts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("fact_type", sa.String(length=64), nullable=False),
        sa.Column("literal", sa.String(length=512), nullable=False),
        sa.Column("numeric_value", sa.Numeric(precision=20, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("page", sa.Integer(), nullable=False),
        sa.Column("span_start", sa.Integer(), nullable=False),
        sa.Column("span_end", sa.Integer(), nullable=False),
        sa.Column("snippet", sa.Text(), nullable=False),
        sa.Column("method", sa.String(length=128), nullable=False),
        sa.Column("extractor", sa.String(length=64), nullable=False),
        sa.Column("extractor_version", sa.String(length=32), nullable=False),
        sa.Column(
            "extracted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency IS NULL OR currency = upper(currency)",
            name=op.f("ck_extracted_facts_currency_is_upper"),
        ),
        sa.CheckConstraint("page >= 1", name=op.f("ck_extracted_facts_page_is_one_based")),
        sa.CheckConstraint("span_end >= span_start", name=op.f("ck_extracted_facts_span_is_whole")),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_extracted_facts_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_extracted_facts")),
        sa.UniqueConstraint(
            "document_id",
            "fact_type",
            "extractor_version",
            name="one_fact_per_type_per_extractor_version",
        ),
    )
    op.create_index(
        op.f("ix_extracted_facts_document_id"), "extracted_facts", ["document_id"], unique=False
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.String(length=32), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("expected", sa.String(length=256), nullable=False),
        sa.Column("observed", sa.String(length=256), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "evaluated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('pass', 'fail', 'inconclusive')", name=op.f("ck_findings_outcome_is_known")
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_findings_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint(
            "document_id", "rule_id", "rule_version", name="one_finding_per_rule_version"
        ),
    )
    op.create_index(op.f("ix_findings_document_id"), "findings", ["document_id"], unique=False)
    op.create_index(op.f("ix_findings_outcome"), "findings", ["outcome"], unique=False)
    op.create_table(
        "finding_evidence",
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column("fact_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["fact_id"],
            ["extracted_facts.id"],
            name=op.f("fk_finding_evidence_fact_id_extracted_facts"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_finding_evidence_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("finding_id", "fact_id", name=op.f("pk_finding_evidence")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("finding_evidence")
    op.drop_index(op.f("ix_findings_outcome"), table_name="findings")
    op.drop_index(op.f("ix_findings_document_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_extracted_facts_document_id"), table_name="extracted_facts")
    op.drop_table("extracted_facts")
    # ### end Alembic commands ###
