"""Initial acquisition schema: crawl jobs, documents, discovered URLs.

Revision ID: 0001_initial
Revises: None
Created: 2026-08-17

Hand-written rather than autogenerated, because no PostgreSQL instance was available on the
authoring machine. ``tests/unit/test_migration_matches_models.py`` compares the DDL this
emits against ``Base.metadata`` offline, and CI additionally runs ``alembic upgrade head``
followed by ``alembic check`` against real PostgreSQL to prove the two have not drifted.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "crawl_jobs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("urls_discovered", sa.Integer(), nullable=False),
        sa.Column("documents_stored", sa.Integer(), nullable=False),
        sa.Column("documents_duplicate", sa.Integer(), nullable=False),
        sa.Column("documents_failed", sa.Integer(), nullable=False),
        sa.Column("checkpoint", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("software_version", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "urls_discovered >= 0 AND documents_stored >= 0 "
            "AND documents_duplicate >= 0 AND documents_failed >= 0",
            name=op.f("ck_crawl_jobs_counters_non_negative"),
        ),
        sa.CheckConstraint(
            "(status = 'running') = (finished_at IS NULL)",
            name=op.f("ck_crawl_jobs_finished_at_matches_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crawl_jobs")),
    )
    op.create_index(op.f("ix_crawl_jobs_source_id"), "crawl_jobs", ["source_id"], unique=False)
    op.create_index("ix_crawl_jobs_source_started", "crawl_jobs", ["source_id", "started_at"])
    op.create_index(op.f("ix_crawl_jobs_status"), "crawl_jobs", ["status"], unique=False)

    op.create_table(
        "documents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("file_format", sa.String(length=16), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=True),
        sa.Column("original_filename", sa.String(length=128), nullable=True),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("document_type", sa.String(length=48), nullable=False),
        sa.Column("document_category", sa.String(length=32), nullable=False),
        sa.Column("classification_confidence", sa.Float(), nullable=True),
        sa.Column("classifier_version", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "classification_confidence IS NULL "
            "OR (classification_confidence >= 0 AND classification_confidence <= 1)",
            name=op.f("ck_documents_confidence_in_range"),
        ),
        sa.CheckConstraint(
            "sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_documents_sha256_is_lower_hex"),
        ),
        sa.CheckConstraint("size_bytes > 0", name=op.f("ck_documents_size_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_documents")),
        sa.UniqueConstraint("sha256", name=op.f("uq_documents_sha256")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_documents_storage_key")),
    )
    op.create_index(op.f("ix_documents_state"), "documents", ["state"], unique=False)
    op.create_index("ix_documents_type_state", "documents", ["document_type", "state"])

    op.create_table(
        "discovered_urls",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_sha256", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_attempted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("downloaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("error_type", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_discovered_urls_attempts_non_negative")),
        sa.CheckConstraint(
            "document_id IS NOT NULL OR state IN "
            "('discovered', 'downloading', 'failed', 'quarantined')",
            name=op.f("ck_discovered_urls_document_required_after_download"),
        ),
        sa.CheckConstraint(
            "url_sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_discovered_urls_url_sha256_is_lower_hex"),
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_discovered_urls_document_id_documents"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["crawl_jobs.id"],
            name=op.f("fk_discovered_urls_job_id_crawl_jobs"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_discovered_urls")),
        sa.UniqueConstraint(
            "source_id", "url_sha256", name=op.f("uq_discovered_urls_source_id_url_sha256")
        ),
    )
    op.create_index(
        op.f("ix_discovered_urls_document_id"), "discovered_urls", ["document_id"], unique=False
    )
    op.create_index(op.f("ix_discovered_urls_job_id"), "discovered_urls", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_discovered_urls_source_id"), "discovered_urls", ["source_id"], unique=False
    )
    op.create_index(op.f("ix_discovered_urls_state"), "discovered_urls", ["state"], unique=False)
    op.create_index("ix_discovered_urls_state_source", "discovered_urls", ["state", "source_id"])


def downgrade() -> None:
    op.drop_index("ix_discovered_urls_state_source", table_name="discovered_urls")
    op.drop_index(op.f("ix_discovered_urls_state"), table_name="discovered_urls")
    op.drop_index(op.f("ix_discovered_urls_source_id"), table_name="discovered_urls")
    op.drop_index(op.f("ix_discovered_urls_job_id"), table_name="discovered_urls")
    op.drop_index(op.f("ix_discovered_urls_document_id"), table_name="discovered_urls")
    op.drop_table("discovered_urls")

    op.drop_index("ix_documents_type_state", table_name="documents")
    op.drop_index(op.f("ix_documents_state"), table_name="documents")
    op.drop_table("documents")

    op.drop_index(op.f("ix_crawl_jobs_status"), table_name="crawl_jobs")
    op.drop_index("ix_crawl_jobs_source_started", table_name="crawl_jobs")
    op.drop_index(op.f("ix_crawl_jobs_source_id"), table_name="crawl_jobs")
    op.drop_table("crawl_jobs")
