"""add work items uploads and payment facts

Revision ID: 3ba3e533dba4
Revises: da09a68e4233
Created: 2026-08-20 18:33:32.070585+00:00

Downgrade must be implemented and must be tested. A migration that cannot be reversed is a
migration that cannot be safely deployed.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3ba3e533dba4"
down_revision: str | None = "da09a68e4233"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_uploads",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("document_id", sa.Uuid(), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=False),
        sa.Column("original_path", sa.Text(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("uploaded_by", sa.String(length=128), nullable=False),
        sa.Column("storage_bucket", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("storage_verification", sa.String(length=32), nullable=False),
        sa.Column("software_version", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
            name=op.f("fk_document_uploads_document_id_documents"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_document_uploads")),
        sa.UniqueConstraint("document_id", "source_id", name="one_upload_per_document_and_source"),
    )
    op.create_index(
        op.f("ix_document_uploads_document_id"), "document_uploads", ["document_id"], unique=False
    )
    op.create_index(
        op.f("ix_document_uploads_source_id"), "document_uploads", ["source_id"], unique=False
    )
    op.create_table(
        "work_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("item_identifier", sa.String(length=64), nullable=False),
        sa.Column("normalised_identifier", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=16), nullable=True),
        sa.Column("matched_by", sa.String(length=64), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_work_items_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_items")),
        sa.UniqueConstraint(
            "project_id", "normalised_identifier", name="one_work_item_per_project_identifier"
        ),
    )
    op.create_index(op.f("ix_work_items_project_id"), "work_items", ["project_id"], unique=False)
    op.add_column("extracted_facts", sa.Column("sheet_row", sa.Integer(), nullable=True))
    # The old constraint assumed one fact of each type per document, which is true of prose and
    # false of a table: a three-row bill of quantities persisted only its last row. Replaced by two
    # partial indexes so page facts keep deduplicating while table rows are distinguished.
    op.drop_constraint(
        op.f("one_fact_per_type_per_extractor_version"), "extracted_facts", type_="unique"
    )
    op.add_column("extracted_facts", sa.Column("sheet_column", sa.Integer(), nullable=True))
    op.add_column("extracted_facts", sa.Column("unit", sa.String(length=16), nullable=True))
    op.add_column("extracted_facts", sa.Column("work_item_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_extracted_facts_work_item_id"), "extracted_facts", ["work_item_id"], unique=False
    )
    op.create_index(
        "uq_extracted_facts_document_type",
        "extracted_facts",
        ["document_id", "fact_type", "extractor_version"],
        unique=True,
        postgresql_where=sa.text("sheet_row IS NULL"),
    )
    op.create_index(
        "uq_extracted_facts_document_type_row",
        "extracted_facts",
        ["document_id", "fact_type", "extractor_version", "sheet_row"],
        unique=True,
        postgresql_where=sa.text("sheet_row IS NOT NULL"),
    )
    op.create_foreign_key(
        op.f("fk_extracted_facts_work_item_id_work_items"),
        "extracted_facts",
        "work_items",
        ["work_item_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column("findings", sa.Column("work_item_id", sa.Uuid(), nullable=True))

    # Two *modifications* autogenerate cannot see, because Alembic compares check constraints and
    # indexes by name rather than by definition. Both were missed on the first run of this migration
    # and are written by hand; without them the database would keep enforcing the old rules while
    # the models claimed the new ones.
    #
    # 1. The outcome vocabulary gains 'review'. A payment discrepancy is neither a pass nor a
    #    failure -- the rule can establish it but not its cause -- and without this the database
    #    would reject every reconciliation finding.
    op.drop_constraint(op.f("ck_findings_outcome_is_known"), "findings", type_="check")
    op.create_check_constraint(
        op.f("ck_findings_outcome_is_known"),
        "findings",
        "outcome IN ('pass', 'fail', 'review', 'inconclusive')",
    )

    # 2. The project-scope unique index must exclude work-item findings, which carry project_id too.
    #    Left as it was, two items checked by one rule would collide on the second insert.
    op.drop_index(
        "uq_findings_project_rule",
        table_name="findings",
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.create_index(
        "uq_findings_project_rule",
        "findings",
        ["project_id", "rule_id", "rule_version"],
        unique=True,
        postgresql_where=sa.text("project_id IS NOT NULL AND work_item_id IS NULL"),
    )
    op.create_index(op.f("ix_findings_work_item_id"), "findings", ["work_item_id"], unique=False)
    op.create_index(
        "uq_findings_work_item_rule",
        "findings",
        ["work_item_id", "rule_id", "rule_version"],
        unique=True,
        postgresql_where=sa.text("work_item_id IS NOT NULL"),
    )
    op.create_foreign_key(
        op.f("fk_findings_work_item_id_work_items"),
        "findings",
        "work_items",
        ["work_item_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_check_constraint(
        op.f("ck_findings_work_item_finding_belongs_to_a_project"),
        "findings",
        "work_item_id IS NULL OR project_id IS NOT NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Reverse both hand-written modifications, and drop the findings the old vocabulary cannot hold.
    # A 'review' outcome has no representation in the previous check constraint, so those rows go
    # before it is restored -- derived evidence, rebuilt by re-running the analysis.
    op.execute("DELETE FROM findings WHERE outcome = 'review' OR work_item_id IS NOT NULL")
    op.drop_index(
        "uq_findings_project_rule",
        table_name="findings",
        postgresql_where=sa.text("project_id IS NOT NULL AND work_item_id IS NULL"),
    )
    op.create_index(
        "uq_findings_project_rule",
        "findings",
        ["project_id", "rule_id", "rule_version"],
        unique=True,
        postgresql_where=sa.text("project_id IS NOT NULL"),
    )
    op.drop_constraint(op.f("ck_findings_outcome_is_known"), "findings", type_="check")
    op.create_check_constraint(
        op.f("ck_findings_outcome_is_known"),
        "findings",
        "outcome IN ('pass', 'fail', 'inconclusive')",
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_findings_work_item_finding_belongs_to_a_project"), "findings", type_="check"
    )
    op.drop_constraint(op.f("fk_findings_work_item_id_work_items"), "findings", type_="foreignkey")
    op.drop_index(
        "uq_findings_work_item_rule",
        table_name="findings",
        postgresql_where=sa.text("work_item_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_findings_work_item_id"), table_name="findings")
    op.drop_column("findings", "work_item_id")
    op.drop_constraint(
        op.f("fk_extracted_facts_work_item_id_work_items"), "extracted_facts", type_="foreignkey"
    )
    op.drop_index(op.f("ix_extracted_facts_work_item_id"), table_name="extracted_facts")
    op.drop_column("extracted_facts", "work_item_id")
    op.drop_column("extracted_facts", "unit")
    op.drop_column("extracted_facts", "sheet_column")
    op.drop_index(
        "uq_extracted_facts_document_type_row",
        table_name="extracted_facts",
        postgresql_where=sa.text("sheet_row IS NOT NULL"),
    )
    op.drop_index(
        "uq_extracted_facts_document_type",
        table_name="extracted_facts",
        postgresql_where=sa.text("sheet_row IS NULL"),
    )
    # Spreadsheet facts cannot exist under the old constraint, which permits one fact of each type
    # per document -- a three-row bill of quantities needs three. They are removed before it is
    # restored. Found by reversing this migration against real data, like the two before it.
    #
    # Sound because these are extractions, rebuilt by re-running the analysis over artifacts that
    # are untouched here. No raw document, no provenance row, and nothing acquired is removed.
    # Order matters, and the constraints enforce it. derived_fact_inputs holds ON DELETE RESTRICT on
    # the fact, deliberately -- a computed value must not outlive the evidence it came from. So the
    # derived facts built from spreadsheet rows go first, and their input links and any citing
    # evidence follow by cascade. The work-item findings that cite them were already removed above.
    op.execute("""
        DELETE FROM derived_facts WHERE id IN (
            SELECT inputs.derived_fact_id
            FROM derived_fact_inputs AS inputs
            JOIN extracted_facts AS facts ON facts.id = inputs.fact_id
            WHERE facts.sheet_row IS NOT NULL
        )
        """)
    op.execute("DELETE FROM extracted_facts WHERE sheet_row IS NOT NULL")
    op.create_unique_constraint(
        op.f("one_fact_per_type_per_extractor_version"),
        "extracted_facts",
        ["document_id", "fact_type", "extractor_version"],
    )
    op.drop_column("extracted_facts", "sheet_row")
    op.drop_index(op.f("ix_work_items_project_id"), table_name="work_items")
    op.drop_table("work_items")
    op.drop_index(op.f("ix_document_uploads_source_id"), table_name="document_uploads")
    op.drop_index(op.f("ix_document_uploads_document_id"), table_name="document_uploads")
    op.drop_table("document_uploads")
    # ### end Alembic commands ###
