"""Generate the synthetic construction project used to exercise payment reconciliation.

Run: ``python -m scripts.generate_synthetic_project``

**Everything this produces is fictional.** No real project, contractor, employer, or price appears
in it. The files are written with SYNTHETIC in the filename, a banner row in every sheet, and a
ground-truth file recording exactly which line items were made inconsistent on purpose — so a
reader who finds a discrepancy can tell whether it is the dataset's or the pipeline's.

The dataset is deliberately tiny: three documents, three work items. Two agree; one does not. That
is enough to exercise the whole path and small enough that a person can verify the expected result
by hand, which is the only way to know the pipeline is right rather than merely consistent.

Kept as a script rather than a fixture because the files are inputs to the *product*, not to the
test suite: they get ingested, stored, hashed, and analysed exactly as a real document would be.

Regeneration must be **byte-identical**, and that took work rather than merely avoiding a random
seed. openpyxl stamps a creation time into every workbook, so the first version of this script
produced a different SHA-256 on every run — which in a content-addressed system means a new document
id and a duplicate artifact each time the dataset was regenerated. The timestamps are pinned below
for that reason.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from typing import Final

from openpyxl import Workbook

PROJECT_REF: Final[str] = "AEDX-SYNTH-001"
OUTPUT_DIR: Final[Path] = Path("data/synthetic") / PROJECT_REF

# Pinned so the workbook bytes do not change between runs. Any fixed instant would do; this is the
# date the dataset was designed.
GENERATED_AT: Final[datetime] = datetime(2026, 8, 20, tzinfo=UTC)

BANNER: Final[str] = (
    "SYNTHETIC DATA - generated by Aedifex for testing. Fictional project, no real parties."
)


@dataclass(frozen=True, slots=True)
class Item:
    """One work item across all three documents, and what the pipeline should conclude about it.

    A typed record rather than a dict, so the generator needs no casts and no asserts to satisfy a
    type checker -- and so the claimed rate sits beside the contracted one, where a reader can see
    at a glance which items were made to disagree.
    """

    item: str
    description: str
    unit: str
    contracted_quantity: Decimal
    contract_rate: Decimal
    measured_quantity: Decimal
    previous_certified: Decimal
    current_claim: Decimal
    claimed_rate: Decimal
    expectation: str

    @property
    def cumulative_claim(self) -> Decimal:
        return self.previous_certified + self.current_claim


# Two items agree; one overclaims quantity and one overclaims rate. Two different kinds of
# disagreement, so a passing run cannot be mistaken for a rule that only ever passes.
ITEMS: Final[tuple[Item, ...]] = (
    Item(
        item="4.7.1",
        description="Excavation in ordinary soil",
        unit="m3",
        contracted_quantity=Decimal("1200"),
        contract_rate=Decimal("450"),
        measured_quantity=Decimal("1150"),
        previous_certified=Decimal("900"),
        current_claim=Decimal("250"),
        claimed_rate=Decimal("450"),
        expectation="consistent: cumulative 1150 equals measured 1150, rate matches",
    ),
    Item(
        item="4.7.2",
        description="RCC M30 in foundation",
        unit="m3",
        contracted_quantity=Decimal("500"),
        contract_rate=Decimal("8000"),
        measured_quantity=Decimal("470"),
        previous_certified=Decimal("420"),
        current_claim=Decimal("100"),
        claimed_rate=Decimal("8000"),
        # 420 + 100 = 520 claimed against 470 measured: 50 m3 unsupported at 8000 = 400,000.
        expectation="INCONSISTENT (quantity): cumulative 520 exceeds measured 470 by 50 m3",
    ),
    Item(
        item="4.7.3",
        description="Reinforcement steel Fe500D",
        unit="MT",
        contracted_quantity=Decimal("85"),
        contract_rate=Decimal("72000"),
        measured_quantity=Decimal("60"),
        previous_certified=Decimal("40"),
        current_claim=Decimal("20"),
        # Claimed 2500/MT above the contracted rate.
        claimed_rate=Decimal("74500"),
        expectation="INCONSISTENT (rate): claimed 74500 exceeds contracted 72000 by 2500",
    ),
)


def _pin_timestamps(workbook: Workbook) -> None:
    """Freeze the workbook's document properties so its bytes are reproducible."""
    workbook.properties.created = GENERATED_AT
    workbook.properties.modified = GENERATED_AT
    workbook.properties.creator = "aedifex-synthetic-generator"
    workbook.properties.lastModifiedBy = "aedifex-synthetic-generator"


def _sheet(workbook: Workbook, title: str, subtitle: str) -> object:
    _pin_timestamps(workbook)
    sheet = workbook.active
    sheet.title = title
    sheet.append([BANNER])
    sheet.append([f"Project: {PROJECT_REF}"])
    sheet.append([subtitle])
    sheet.append([])
    return sheet


def write_boq(path: Path) -> None:
    """Bill of quantities: what was contracted, at what rate."""
    workbook = Workbook()
    sheet = _sheet(workbook, "BOQ", "BILL OF QUANTITIES")
    sheet.append(["Item No", "Description", "Unit", "Quantity", "Rate", "Amount"])
    for row in ITEMS:
        sheet.append(
            [
                row.item,
                row.description,
                row.unit,
                float(row.contracted_quantity),
                float(row.contract_rate),
                float(row.contracted_quantity * row.contract_rate),
            ]
        )
    workbook.save(path)


def write_measurement(path: Path) -> None:
    """Measurement book extract: what was actually measured on site."""
    workbook = Workbook()
    sheet = _sheet(workbook, "Measurement", "MEASUREMENT BOOK EXTRACT - MB Ref MB/17/2026")
    sheet.append(["Item No", "Description", "Unit", "Measured Quantity", "Measurement Date"])
    for row in ITEMS:
        sheet.append(
            [
                row.item,
                row.description,
                row.unit,
                float(row.measured_quantity),
                "2026-07-31",
            ]
        )
    workbook.save(path)


def write_running_bill(path: Path) -> None:
    """Running account bill: what is being claimed, cumulatively."""
    workbook = Workbook()
    sheet = _sheet(workbook, "RA Bill", "RUNNING ACCOUNT BILL No. 3 - RA/03/2026")
    sheet.append(
        [
            "Item No",
            "Description",
            "Unit",
            "Previous Certified Quantity",
            "Current Claim Quantity",
            "Cumulative Claim Quantity",
            "Rate",
            "Amount",
        ]
    )
    for row in ITEMS:
        sheet.append(
            [
                row.item,
                row.description,
                row.unit,
                float(row.previous_certified),
                float(row.current_claim),
                float(row.cumulative_claim),
                float(row.claimed_rate),
                float(row.cumulative_claim * row.claimed_rate),
            ]
        )
    workbook.save(path)


def write_ground_truth(path: Path) -> None:
    """What was planted, so a discrepancy can be attributed to the data or to the pipeline."""
    payload = {
        "project_reference": PROJECT_REF,
        "synthetic": True,
        "generated_by": "scripts/generate_synthetic_project.py",
        "warning": BANNER,
        "items": [
            {
                "item": row.item,
                "unit": row.unit,
                "contracted_quantity": str(row.contracted_quantity),
                "contract_rate": str(row.contract_rate),
                "measured_quantity": str(row.measured_quantity),
                "previous_certified_quantity": str(row.previous_certified),
                "current_claim_quantity": str(row.current_claim),
                "cumulative_claim_quantity": str(row.cumulative_claim),
                "claimed_rate": str(row.claimed_rate),
                "expectation": row.expectation,
            }
            for row in ITEMS
        ],
        "expected_findings": [
            {
                "item": "4.7.2",
                "rule": "claim_within_measured_quantity",
                "outcome": "review",
                "quantity_variance": "50",
                "unsupported_amount": "400000",
                "explanation": "Cumulative claim 520 m3 exceeds measured 470 m3 at rate 8000.",
            },
            {
                "item": "4.7.3",
                "rule": "claimed_rate_matches_contract_rate",
                "outcome": "review",
                "rate_variance": "2500",
                "explanation": "Claimed rate 74500 exceeds contracted rate 72000.",
            },
        ],
    }
    path.write_text(json.dumps(payload, indent=2) + "\n")


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    write_boq(OUTPUT_DIR / "SYNTHETIC_BOQ_AEDX-SYNTH-001.xlsx")
    write_measurement(OUTPUT_DIR / "SYNTHETIC_Measurement_AEDX-SYNTH-001.xlsx")
    write_running_bill(OUTPUT_DIR / "SYNTHETIC_RA-Bill-03_AEDX-SYNTH-001.xlsx")
    write_ground_truth(OUTPUT_DIR / "GROUND_TRUTH.json")
    for path in sorted(OUTPUT_DIR.iterdir()):
        print(f"wrote {path} ({path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
