"""Generate the synthetic construction project used to exercise payment reconciliation.

Run: ``python -m scripts.generate_synthetic_project``

**Everything this produces is fictional.** No real project, contractor, employer, or price appears
in it. The files are written with SYNTHETIC in the filename, a banner row in every sheet, and a
ground-truth file recording exactly which line items were made inconsistent on purpose — so a
reader who finds a discrepancy can tell whether it is the dataset's or the pipeline's.

The dataset is deliberately tiny: three documents, three work items. Two agree; one does not. That
is enough to exercise the whole path and small enough that a person can verify the expected result
by hand, which is the only way to know the pipeline is right rather than merely consistent.

Kept as a script rather than a fixture because the files are inputs to the *product*, not to the
test suite: they get ingested, stored, hashed, and analysed exactly as a real document would be.

Regeneration must be **byte-identical**, and that took two attempts to get right. In a
content-addressed store a changed byte is a *new document*, so a non-reproducible generator quietly
duplicates the corpus every time anyone runs it.

Three separate sources of nondeterminism had to go, and finding them took three attempts.

openpyxl stamps a creation time into the workbook's document properties. An XLSX *is* a ZIP archive,
and each entry carries a modification time taken from the clock at save. And openpyxl rewrites
``dcterms:modified`` during ``save`` itself, discarding whatever the caller pinned beforehand.

Pinning only the document properties *looked* like a fix, because ZIP timestamps have two-second
resolution and two consecutive runs usually land in the same second — the first verification was
simply too fast to detect the bug. The lesson is in the test rather than the code: reproducibility
has to be checked across a real time gap.
"""

from __future__ import annotations

import json
import re
import zipfile
from dataclasses import dataclass
from datetime import UTC, datetime
from decimal import Decimal
from pathlib import Path
from typing import Final

from openpyxl import Workbook
from openpyxl.worksheet.worksheet import Worksheet

PROJECT_REF: Final[str] = "AEDX-SYNTH-001"
OUTPUT_DIR: Final[Path] = Path("data/synthetic") / PROJECT_REF

# Pinned so the workbook bytes do not change between runs. Any fixed instant would do; this is the
# date the dataset was designed.
GENERATED_AT: Final[datetime] = datetime(2026, 8, 20, tzinfo=UTC)

# The same instant as a ZIP date_time tuple. ZIP stores local time with two-second resolution and no
# zone, which is why this is a separate constant rather than derived from GENERATED_AT at runtime.
ZIP_TIMESTAMP: Final[tuple[int, int, int, int, int, int]] = (2026, 8, 20, 0, 0, 0)

BANNER: Final[str] = (
    "SYNTHETIC DATA - generated by Aedifex for testing. Fictional project, no real parties."
)


@dataclass(frozen=True, slots=True)
class Item:
    """One work item across all three documents, and what the pipeline should conclude about it.

    A typed record rather than a dict, so the generator needs no casts and no asserts to satisfy a
    type checker -- and so the claimed rate sits beside the contracted one, where a reader can see
    at a glance which items were made to disagree.
    """

    item: str
    description: str
    unit: str
    contracted_quantity: Decimal
    contract_rate: Decimal
    measured_quantity: Decimal
    previous_certified: Decimal
    current_claim: Decimal
    claimed_rate: Decimal
    expectation: str

    @property
    def cumulative_claim(self) -> Decimal:
        return self.previous_certified + self.current_claim


# Two items agree; one overclaims quantity and one overclaims rate. Two different kinds of
# disagreement, so a passing run cannot be mistaken for a rule that only ever passes.
ITEMS: Final[tuple[Item, ...]] = (
    Item(
        item="4.7.1",
        description="Excavation in ordinary soil",
        unit="m3",
        contracted_quantity=Decimal("1200"),
        contract_rate=Decimal("450"),
        measured_quantity=Decimal("1150"),
        previous_certified=Decimal("900"),
        current_claim=Decimal("250"),
        claimed_rate=Decimal("450"),
        expectation="consistent: cumulative 1150 equals measured 1150, rate matches",
    ),
    Item(
        item="4.7.2",
        description="RCC M30 in foundation",
        unit="m3",
        contracted_quantity=Decimal("500"),
        contract_rate=Decimal("8000"),
        measured_quantity=Decimal("470"),
        previous_certified=Decimal("420"),
        current_claim=Decimal("100"),
        claimed_rate=Decimal("8000"),
        # 420 + 100 = 520 claimed against 470 measured: 50 m3 unsupported at 8000 = 400,000.
        expectation="INCONSISTENT (quantity): cumulative 520 exceeds measured 470 by 50 m3",
    ),
    Item(
        item="4.7.3",
        description="Reinforcement steel Fe500D",
        unit="MT",
        contracted_quantity=Decimal("85"),
        contract_rate=Decimal("72000"),
        measured_quantity=Decimal("60"),
        previous_certified=Decimal("40"),
        current_claim=Decimal("20"),
        # Claimed 2500/MT above the contracted rate.
        claimed_rate=Decimal("74500"),
        expectation="INCONSISTENT (rate): claimed 74500 exceeds contracted 72000 by 2500",
    ),
)


# dcterms:modified, which openpyxl writes from the clock at save time.
_MODIFIED_ELEMENT: Final[re.Pattern[bytes]] = re.compile(
    rb"(<dcterms:modified[^>]*>)[^<]*(</dcterms:modified>)"
)
_PINNED_STAMP: Final[bytes] = GENERATED_AT.strftime("%Y-%m-%dT%H:%M:%SZ").encode("ascii")


def _normalise_part(filename: str, payload: bytes) -> bytes:
    """Strip clock-derived values from an archive member."""
    if filename != "docProps/core.xml":
        return payload
    return _MODIFIED_ELEMENT.sub(rb"\g<1>" + _PINNED_STAMP + rb"\g<2>", payload)


def _rewrite_archive_deterministically(path: Path) -> None:
    """Rewrite an XLSX so its bytes depend only on its contents.

    An XLSX is a ZIP archive, and openpyxl writes each entry with the clock's current time. Two runs
    a second apart therefore produce different bytes, a different SHA-256, and — in a
    content-addressed store — a different document for identical data.

    Entries are rewritten with a fixed timestamp and in sorted order, so the archive layout is a
    function of the data alone. ``docProps/core.xml`` is also rewritten, because openpyxl sets
    ``dcterms:modified`` from the clock during ``save`` and discards whatever the caller pinned
    beforehand — normalising the final bytes is the only form of this fix that holds regardless of
    what the library does internally.
    """
    with zipfile.ZipFile(path) as source:
        entries = [
            (
                info.filename,
                info.external_attr,
                _normalise_part(info.filename, source.read(info.filename)),
            )
            for info in sorted(source.infolist(), key=lambda item: item.filename)
        ]

    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as target:
        for filename, external_attr, payload in entries:
            info = zipfile.ZipInfo(filename, date_time=ZIP_TIMESTAMP)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = external_attr
            target.writestr(info, payload)


def _save(workbook: Workbook, path: Path) -> None:
    """Save a workbook reproducibly."""
    workbook.save(path)
    _rewrite_archive_deterministically(path)


def _pin_timestamps(workbook: Workbook) -> None:
    """Freeze the workbook's document properties so its bytes are reproducible."""
    workbook.properties.created = GENERATED_AT
    workbook.properties.modified = GENERATED_AT
    workbook.properties.creator = "aedifex-synthetic-generator"
    workbook.properties.lastModifiedBy = "aedifex-synthetic-generator"


def _sheet(workbook: Workbook, title: str, subtitle: str) -> Worksheet:
    """Prepare the workbook's first sheet with the banner rows every file carries.

    ``Workbook.active`` is optional in openpyxl's type stubs — a workbook can hold a chartsheet, or
    none at all — so the narrowing is real rather than ceremonial, even though a freshly constructed
    workbook always has exactly one worksheet.
    """
    _pin_timestamps(workbook)
    sheet = workbook.active
    if not isinstance(sheet, Worksheet):  # pragma: no cover - a new Workbook always has one
        raise TypeError("a new workbook unexpectedly has no active worksheet")
    sheet.title = title
    sheet.append([BANNER])
    sheet.append([f"Project: {PROJECT_REF}"])
    sheet.append([subtitle])
    sheet.append([])
    return sheet


def write_boq(path: Path) -> None:
    """Bill of quantities: what was contracted, at what rate."""
    workbook = Workbook()
    sheet = _sheet(workbook, "BOQ", "BILL OF QUANTITIES")
    sheet.append(["Item No", "Description", "Unit", "Quantity", "Rate", "Amount"])
    for row in ITEMS:
        sheet.append(
            [
                row.item,
                row.description,
                row.unit,
                float(row.contracted_quantity),
                float(row.contract_rate),
                float(row.contracted_quantity * row.contract_rate),
            ]
        )
    _save(workbook, path)


def write_measurement(path: Path) -> None:
    """Measurement book extract: what was actually measured on site."""
    workbook = Workbook()
    sheet = _sheet(workbook, "Measurement", "MEASUREMENT BOOK EXTRACT - MB Ref MB/17/2026")
    sheet.append(["Item No", "Description", "Unit", "Measured Quantity", "Measurement Date"])
    for row in ITEMS:
        sheet.append(
            [
                row.item,
                row.description,
                row.unit,
                float(row.measured_quantity),
                "2026-07-31",
            ]
        )
    _save(workbook, path)


def write_running_bill(path: Path) -> None:
    """Running account bill: what is being claimed, cumulatively."""
    workbook = Workbook()
    sheet = _sheet(workbook, "RA Bill", "RUNNING ACCOUNT BILL No. 3 - RA/03/2026")
    sheet.append(
        [
            "Item No",
            "Description",
            "Unit",
            "Previous Certified Quantity",
            "Current Claim Quantity",
            "Cumulative Claim Quantity",
            "Rate",
            "Amount",
        ]
    )
    for row in ITEMS:
        sheet.append(
            [
                row.item,
                row.description,
                row.unit,
                float(row.previous_certified),
                float(row.current_claim),
                float(row.cumulative_claim),
                float(row.claimed_rate),
                float(row.cumulative_claim * row.claimed_rate),
            ]
        )
    _save(workbook, path)


# Item 4.7.2's contracted quantity is revised upward. The revision is what makes the reconciliation
# change: against Rev 01 the cumulative claim of 520 exceeds a 500 contract; against Rev 02 it does
# not. So "which revision governs" is not academic here -- it changes the finding.
REVISED_QUANTITIES: Final[dict[str, Decimal]] = {"4.7.2": Decimal("550")}


def write_revised_boq(path: Path) -> None:
    """BOQ Rev 02: the same items, with item 4.7.2's quantity revised from 500 to 550.

    Written as a genuinely separate document rather than an edit, because that is what happens on a
    real project — the original is issued, then a revision is issued, and both exist.
    """
    workbook = Workbook()
    sheet = _sheet(workbook, "BOQ", "BILL OF QUANTITIES - REVISION 02")
    sheet.append(["Item No", "Description", "Unit", "Quantity", "Rate", "Amount"])
    for row in ITEMS:
        quantity = REVISED_QUANTITIES.get(row.item, row.contracted_quantity)
        sheet.append(
            [
                row.item,
                row.description,
                row.unit,
                float(quantity),
                float(row.contract_rate),
                float(quantity * row.contract_rate),
            ]
        )
    _save(workbook, path)


def write_unlinked_duplicate_boq(path: Path) -> None:
    """A third bill of quantities that conflicts with the others and supersedes nothing.

    The ambiguous case. Two active documents state different contracted quantities for item 4.7.1
    and no supersession relationship exists between them, which is the situation a real project
    reaches whenever someone uploads a revision without recording that it is one.

    Aedifex must refuse to reconcile that item rather than pick a side. This file exists to prove it
    refuses.
    """
    workbook = Workbook()
    sheet = _sheet(workbook, "BOQ", "BILL OF QUANTITIES - UNRECORDED VARIANT")
    sheet.append(["Item No", "Description", "Unit", "Quantity", "Rate", "Amount"])
    for row in ITEMS:
        if row.item != "4.7.1":
            continue
        # Differs from both Rev 01 and Rev 02, and nothing declares which is current.
        quantity = Decimal("1400")
        sheet.append(
            [
                row.item,
                row.description,
                row.unit,
                float(quantity),
                float(row.contract_rate),
                float(quantity * row.contract_rate),
            ]
        )
    _save(workbook, path)


def write_ground_truth(path: Path) -> None:
    """What was planted, so a discrepancy can be attributed to the data or to the pipeline."""
    payload = {
        "project_reference": PROJECT_REF,
        "synthetic": True,
        "generated_by": "scripts/generate_synthetic_project.py",
        "warning": BANNER,
        "items": [
            {
                "item": row.item,
                "unit": row.unit,
                "contracted_quantity": str(row.contracted_quantity),
                "contract_rate": str(row.contract_rate),
                "measured_quantity": str(row.measured_quantity),
                "previous_certified_quantity": str(row.previous_certified),
                "current_claim_quantity": str(row.current_claim),
                "cumulative_claim_quantity": str(row.cumulative_claim),
                "claimed_rate": str(row.claimed_rate),
                "expectation": row.expectation,
            }
            for row in ITEMS
        ],
        "revision_scenario": {
            "revised_item": "4.7.2",
            "original_contracted_quantity": "500",
            "revised_contracted_quantity": "550",
            "note": (
                "With BOQ Rev 02 active and Rev 01 superseded, the cumulative claim of 520 is "
                "within the contracted 550 and the quantity variance against measured work is "
                "unchanged at +50. Against Rev 01 the claim also exceeded the contract. The "
                "revision changes remaining_contract_quantity from -20 to +30."
            ),
        },
        "ambiguous_scenario": {
            "item": "4.7.1",
            "conflicting_quantities": ["1200", "1400"],
            "note": (
                "Two active bills of quantities state different contracted quantities for 4.7.1 "
                "and neither supersedes the other. Expected outcome is REVIEW naming both "
                "documents, never an arbitrary choice."
            ),
        },
        "expected_findings": [
            {
                "item": "4.7.2",
                "rule": "claim_within_measured_quantity",
                "outcome": "review",
                "quantity_variance": "50",
                "unsupported_amount": "400000",
                "explanation": "Cumulative claim 520 m3 exceeds measured 470 m3 at rate 8000.",
            },
            {
                "item": "4.7.3",
                "rule": "claimed_rate_matches_contract_rate",
                "outcome": "review",
                "rate_variance": "2500",
                "explanation": "Claimed rate 74500 exceeds contracted rate 72000.",
            },
        ],
    }
    path.write_text(json.dumps(payload, indent=2) + "\n")


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    write_boq(OUTPUT_DIR / "SYNTHETIC_BOQ-Rev01_AEDX-SYNTH-001.xlsx")
    write_revised_boq(OUTPUT_DIR / "SYNTHETIC_BOQ-Rev02_AEDX-SYNTH-001.xlsx")
    write_unlinked_duplicate_boq(OUTPUT_DIR / "SYNTHETIC_BOQ-Unlinked_AEDX-SYNTH-001.xlsx")
    write_measurement(OUTPUT_DIR / "SYNTHETIC_Measurement_AEDX-SYNTH-001.xlsx")
    write_running_bill(OUTPUT_DIR / "SYNTHETIC_RA-Bill-03_AEDX-SYNTH-001.xlsx")
    write_ground_truth(OUTPUT_DIR / "GROUND_TRUTH.json")
    for path in sorted(OUTPUT_DIR.iterdir()):
        print(f"wrote {path} ({path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
